default_context:
  email: corinnet@alleninstitute.org
  full_name: Corinne Teeter
  open_source_license: Allen Institute Software License
  project_name: ephys_pink_noise
  project_namespace: aibs
  project_short_description: Creates the pink noise stimuli used in the noise1, noise2, and ramp to rheo stimulus used in the Allen Institute for Brain Science electrophysiology pipeline.
  project_slug: ephys_pink_noise
  repo_url: https://github.com/AllenInstitute/aibs.ephys_pink_noise
  user_name: corinnet
  version: 0.1.0